name: blog

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.7
  - flask
  - frozen-flask
  - pygments
  - markdown-checklist
  - pip
  - pip:
    - flask-flatpages
    - bootstrap-flask
